
services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: MyVerySecretPassword
      POSTGRES_DB: my_db
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  s3:
    image: minio/minio:RELEASE.2023-11-01T18-37-25Z
    container_name: tasqana_s3
    restart: always
    environment:
      MINIO_ROOT_USER: minio_admin_user      
      MINIO_ROOT_PASSWORD: super_secure_s3_password_123
      MINIO_SERVER_URL: "https://s3.example.com"
      MINIO_BROWSER_REDIRECT_URL: "https://s3.console.example.com"
      
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    volumes:
      - s3_data:/data
    command: server /data --console-address ":9001"

  webapi:
    build:
      context: . 
      dockerfile: Dockerfile     
    restart: always
    ports:
      - "127.0.0.1:5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      PostgresConnectionData__Host: "db" 
      PostgresConnectionData__Port: "5432"
      PostgresConnectionData__Database: "my_db"
      PostgresConnectionData__Username: "my_user"
      PostgresConnectionData__Password: "MyVerySecretPassword"
      Telegram__BotToken: "00000000:AAAAA_bbbbbbbbbbbb-ccccccccccccccccc"  
      Telegram__WebhookSecret: "aaaaaabbbbbbbbbbbbbccccccccccccccdddddddddd"
      Host__Dns: "example.com"  
      S3Settings__Endpoint: "https://s3.example.com"
      S3Settings__BucketName: "tasqana-s3"
      S3Settings__AccessKey: "minio_admin_user"
      S3Settings__SecretKey: "super_secure_s3_password_123"
    depends_on:
      - db

volumes:
  s3_data: 